# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-02 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220501_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
