# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-06 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220505_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, unique=True, verbose_name='Наименование сатуса')),
                ('colorHEX', models.CharField(max_length=6, verbose_name='Цвет статуса HEX')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы заданий',
                'db_table': 'Statuses',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 6, 21, 35, 19, 519169), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 6, 21, 35, 19, 518172), verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='done',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Status', verbose_name='Статус'),
        ),
    ]
