# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-11 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220509_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='colorHEX',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 11, 20, 25, 37, 779009), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 11, 20, 25, 37, 779009), verbose_name='Опубликован'),
        ),
    ]
